version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./ui/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=threats
    command: mongod --bind_ip 0.0.0.0 --auth

  nodejs:
    build: ./ui
    container_name: nodejs
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/usr/src/app
    depends_on:
      - mongodb

volumes:
  mongodb_data:
